### PR TITLE
Add `--pull-json-interval=SECONDS` option to `theme serve`

### PR DESCRIPTION
**Pull request by macournoyer**
To pull remote JSON files for updates at an interval.

### WHY are these changes introduced?

When developing a theme with `shopify theme serve`, changes made in the Editor/Customizer are not reflected locally.

Changed made to the files locally are reflected in the Editor, because JSON files are upload from the local machine to the Editor. But when the Editor modifies a JSON file in the themes, those changes are not pulled into the local machine.

### WHAT is this pull request doing?

Starting the `theme serve` command with:

```
shopify theme --pull-json-interval=3
```

Will pull for any change made remotely on any `.json` file.

For example, if you change the order of sections on the product page, `templates/product.json` will be pulled locally and overwrite the local version of the file.

### Update checklist

- [ ] I've added a CHANGELOG entry for this PR (if the change is public-facing)
- [ ] I've considered possible cross-platform impacts (Mac, Linux, Windows).
- [ ] I've left the version number as is (we'll handle incrementing this when releasing).
- [ ] I've included any post-release steps in the section above.

### CODE REVIEW

**Comment by ADTC** [comment]
Hopefully you can answer these questions above so I can understand this PR better. Will this only work with `theme serve`? What happens if there are simultaneous edits in both your local PC and the remote Shopify admin before the next pull?

**Comment by thomfoolery** [comment]
This is great. A couple questions tho, 
Would it be worth providing a smart default value for the interval? 
With a command like `shopify theme serve --sync` or `shopify theme serve -s`?
Is there still the chance for the remote pull to blow away local changes? and if so, is that communicated to the user?

**Comment by ADTC** [comment]
> Is there still the chance for the remote pull to blow away local changes?

I have the same question.

**Comment by thomfoolery** [comment]
From what I gathered in an associated issue #1434, people were frustrated with their local work being lost when they pulled down changes, not realizing it would blow away their local edits. 

Now this might be a more involved solution requiring it's own issue, but couldn't we detect local changes being present in the settings file with git before pulling down the changes? 

If local changes were detectable, we could
  a) alert the user in the console that the sync was aborted due to local changes being present
  b) prompt the user in the console to manually to stash and then apply their changes before after pulling down the latest settings 
  c) automate stashing and applying their local changes for them

**Comment by ADTC** [comment]
@macournoyer you see, this problem of "conflict" is what Linus Torvalds solved in Git 16 years ago. We'd be reinventing the wheel here 😄

@thomfoolery that's exactly what I propose in #1682 as "Git-awareness" 🙃

**Comment by macournoyer** [comment]
I think we're mixing two problems here. IMO the chance of conflict with this feature (in this PR) is very small. But that's a good point, we should definitely prevent it, or warn about it. But no need to handle merging or stashing.

If you're talking about conflicts with `theme push` & `theme pull`, but really want Git-awarness, you should be using our GitHub integration.

**Comment by ADTC** [comment]
Regarding GitHub Integration, my reply: https://github.com/Shopify/shopify-cli/issues/1682#issuecomment-965348046

> **I dislike the fact that Shopify chose to integrate with a single proprietary service like GitHub instead of the entire Git-based ecosystem.**
> It also doesn't work where GitHub is simply not used (or not even allowed, such as in a corporate environment where BitBucket is used instead).

**Comment by pablogiralt** [comment]
+1

**Comment by macournoyer** [comment]
Superseded by #2174

**Pull request closed without merging**
