### PR TITLE
Improve check of dependency versions

### PR DESCRIPTION
**Pull request by gonzaloriestra**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/shopify-cli/issues/2063

- To avoid errors when the version outputs include warnings or other messages
- To improve the error shown when dependencies are missing (like `Errno::ENOENT: No such file or directory - node`)

### WHAT is this pull request doing?

- Use regex to extract the version number
- Show a `X is required to continue` message when the `X --version` command fails

### How to test your changes?

Uninstall and play with different versions of ruby, rails, node, and npm

### Update checklist

- [x] I've added a CHANGELOG entry for this PR (if the change is public-facing)
- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows).
- [x] I've left the version number as is (we'll handle incrementing this when releasing).
- [x] I've included any post-release steps in the section above.

### CODE REVIEW

**Comment by ADTC** [comment]
I'm assuming this is **not** in **2.14.0**?

**Comment by gonzaloriestra** [comment]
@ADTC no, it will be included in the next release.

You can check the changes from 2.14.0 here: https://github.com/Shopify/shopify-cli/releases/tag/v2.14.0

**Comment by gonzaloriestra** [comment]
@ADTC it should be fixed in [v2.15.0](https://github.com/Shopify/shopify-cli/releases/tag/v2.15.0).

**Comment by ADTC** [comment]
Thank you 💕

**Pull request merged**
