### PR TITLE
Add `--development` flag to Shopify theme pull command

### LINKED ISSUE #1878: [Min feature] Add --development flag to shopify theme pull command
# Issue summary

Write a short description of the issue here ↓

I've been using Shopify CLI and Github integration almost daily, great tools, thanks for the all the maintainers. The other day, I was working with a Shopify Plus merchant, they have almost 100 themes, and usually my workflow is I run the Shopify theme serve command, then make changes wether it's in the customiser/editor or just in code, but before I turn off the development server, I first pull the saved settings in the customiser with the command `shopify theme pull -n` , this prompt me to select a theme to pull from, but imagine if there is 100 themes or you choose a different theme by mistake. Is it possible to add a flag like with the `--live` but instead `--development` that will be extremely helpfull.

## Expected behavior

What do you think should happen?

`shopify theme pull --development`

Pulls the development theme and chooses the theme without prompting the theme selector.

## Actual behavior

What actually happens?

It's a feature request, there is no implementation for it yet.

## Specifications

- App type:
- Operating System: macOs
- Shell: zsh
- Ruby version (ruby -v): v2.6.8p205

### PR DESCRIPTION
**Pull request by idbakkasse**
### WHY are these changes introduced?

This fixes #1878: Users can't pull the changes from the current development theme to save them after making modification on the local theme customiser.

This saves so much time, and might prevent pulling a different theme especially in stores with 100 themes. 

### WHAT is this pull request doing?

This PR introduces a new flag representing the development theme `-d/--development`. So, now users can perform operations like `shopify theme pull --development` to retrieve the settings made in local theme customiser without being prompt to select/choose the development theme (works just like the `--live` flag)

### How to test your changes?

To test the changes run the following commands after lunching the development server

```shell
shopify theme pull --development
or 
shopify theme pull -d
```

### Post-release steps

Update documentation with the new -d/--development flag at https://shopify.dev/themes/tools/cli/theme-commands#pull

### Update checklist

- [ ] I've added a CHANGELOG entry for this PR (if the change is public-facing)
- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows).
- [x] I've left the version number as is (we'll handle incrementing this when releasing).
- [x] I've included any post-release steps in the section above.

### CODE REVIEW

**Comment by younessidbakkasse** [comment]
I tried to sign Shopify CLA but each time I get this Error.

Capture d’écran 2021-12-29 à 11 20 17

**Review by karreiro — COMMENTED** [review]
Thank you for this PR, @idbakkasse 🚀 It's a great enhancement to the development experience!

Also, I'd like to mention some details.

#### 1. `Theme.development` method
The `ShopifyCLI::Theme::Theme.development` method doesn't exist, so when I test it locally (with `shopify theme pull -d'), I see this error:

```
pull.rb:29:in `call': undefined method `development' for
  ShopifyCLI::Theme::Theme:Class (NoMethodError)
```

It will probably be quite similar to the `Theme.live` method in the [`theme.rb`](https://github.com/Shopify/shopify-cli/blob/main/lib/shopify_cli/theme/theme.rb#L175-L181).


#### 2. `theme pull` and `theme push` 
It's nice to keep `pull` and `push` commands synced in this kind of use case, so users may expect that if something works for `pull`, it works for `push` as well. Thus, we could also add the `--development` flag in the [`push.rb`](https://github.com/Shopify/shopify-cli/blob/main/lib/project_types/theme/commands/push.rb#L13).


#### 3. Unit test
Finally, it would be nice to have unit tests for this new flag. It can be something like [this](https://github.com/Shopify/shopify-cli/blob/1055e4c1edcbbef902f745b123aedf4abb039b9a/test/project_types/theme/commands/pull_test.rb#L46-L65), but for the `--development` flag :) 

Thanks again for this PR! It

**Comment by pepicrft** [comment]
Thanks for your contribution @idbakkasse. Helping with the CLA issue, are you using the same email that's associated with your GitHub account when signing the CLA agreement? If you are, try to push another commit. When agreements have been signed the status of the commit doesn't get updated until you push a new commit.

**Comment by idbakkasse** [comment]
Ok I will try that @pepicrft. Thanks for the help.

**Comment by idbakkasse** [comment]
I closed this PR because I had issue with Shopify CLA. Here is the new PR #1900  with all your feedback in. Thanks for your feedback.

**Pull request closed without merging**
