### PR TITLE
Add optional 2-way sync between the CLI (`theme serve`) and the Theme Editor

### LINKED ISSUE #1394: Shopify theme serve unpublished theme
# Issue summary

Is serving an unpublished theme currently possible? Sometimes when i'm dev'ing I'm wanting to use an unpublished theme with different customizer data than that of the published theme.

## Expected behavior

`shopify theme serve [theme id]`

## Actual behavior

No parameter is allowed for this `shopify theme serve` and customizer data is pulled from the published theme.

## Steps to reproduce the problem

1. Duplicate Dawn
2. Change customizer data for duplicate
3. `shopify theme pull` and select duplicate theme.
4. `shopify theme serve`
5. Observe customizer data from published theme while working on a development theme of the unpublished theme.

### LINKED ISSUE #1434: Local customized theme's data not being saved in settings_data.json
# Issue summary

We can view the development them in _http://127.0.0.1:9292/_ and changes made in _https://[sitename].myshopify.com/admin/themes/12345xxxxxx/editor_ are also reflected in http://127.0.0.1:9292/ once saved but the values are not being saved in settings_data.json

So, when 'shopify theme push' is executed in CLI no customized changes are uploaded in live theme.

## Expected behavior
All changes that are saved and reflected in _http://127.0.0.1:9292/_ must be saved in _settings_data.json_ and pushed to live site.

## Actual behavior
Customized changes from editor are not being saved in local _settings_data.json_ and when theme is pushed there is not any change visible in live site.

## Steps to reproduce the problem

1. Serve the theme in localhost (CLI > 'shopify theme serve')
2. Customize theme in editor 
3. Save, stop theme serve and push it in live (CLI > 'shopify theme push')

### LINKED ISSUE #1511: Shopify CLI Store Editor (Store Customizer) not transferring work on "shopify theme push" command
# Issue summary
I worked on a Shopify theme for several hours via the shopify CLI. This was using the command "shopify theme serve". After using that command, the terminal spit out a preview link, and a link to use for the theme editor / customizer. A combination of changes to theme files via liquid / HTML / CSS and edits in the editor / customizer (more in the eiditor / customizer than anything). When I went to run "shopify theme push" I had built out a new home page. The changes I made to theme files transferred via "shopify theme push", but _none_ of the work in the theme editor / customizer transitioned. This effectively lost 3 hours of work. 

## Expected behavior
I expected that all changes I had made via the theme editor spit out by the terminal using "shopify theme serve", which should be building out changes in the config/settings_data.json file, would have transferred to the online store.

## Actual behavior
None of these changes transitioned. I lost all changes made in the theme editor

## Steps to reproduce the problem
1. Open terminal and navigate to a file with shopify theme files. Or, create a new folder and use shopify theme pull to get files from a theme into your local. 
2. run "shopify theme serve" in your terminal. 
3. Make a change using the Online Store Editor link they provide. Save the change. 
4. Stop serving the shopify theme. 
5. Use "shopify theme push" to push the changes from the local to the remote. Make sure to overwrite a theme you don't care about. 
6. Preview the theme on the shopify remote that you just overwrote. The change you made will NOT be there. 

## Specifications
- App type: Shopify
- Operating System: Mac OS Big Sur Version 11.5.2
- Shell: Terminal
- Ruby version (ruby -v): 2.6.3p62

### PR DESCRIPTION
**Pull request by karreiro**
⚠️ I've [split this PR into meaningful commits](https://user-images.githubusercontent.com/1079279/159683112-e01c679d-649d-402f-b9c3-aa1039e24696.png) to make the review process a bit easier (check it with `git log -12`). They do not reflect the order of implementation but a more logical path to follow.

### WHY are these changes introduced?

Currently, when developers run `theme serve`, the CLI replaces the remote development theme with the local version.

Many developers expect that (1-way sync) behavior and already have tooling/workflows relying on that.

However, other developers prefer to rely on a 2-way sync logic. In other words: when something changes in the Theme Editor, the CLI (`theme serve`) should auto get the remote updated version; and when something changes in the local files, the CLI should auto pushes the updated version.

Thus, this PR adds an optional 2-way sync capabilities between the CLI (`theme serve`) and the Theme Editor with the new `--theme-editor-sync` flag.

image

### WHAT is this pull request doing?

This PR approaches the 2-way sync with 3 pillars:

- **1. The `theme serve` startup**
 
  When developers run  `theme serve` with the `--theme-editor-sync` flag, the CLI checks (before pushing the local files to the development theme) if there are changes on remote `.json` files.

  If so, the CLI prompts users to check which version they prefer to keep, or even if they want a merged version of files (ref: `JsonUpdateHandler` and `JsonDeleteHandler`).

- **2. The `theme serve` pulling mechanism**
 
  When developers run  `theme serve` with the `--theme-editor-sync` flag, the CLI adopts will an approach similar to [--pull-json-interval](https://github.com/Shopify/shopify-cli/pull/1708) to pull `.json` files (ref: `RemoteWatcher`).
 
- **3. the Theme Editor conflicts mechanism**

  The CLI already automatically uploads the updated `.json` file when partners locally change them, and the Theme Editor already has a mechanism to avoid conflicts. Thus, no changes will be performed on this side.

#### Goals and non-goals

This PR introduces the `--theme-editor-sync` flag to help developers (that expect 2-way sync features) on avoiding scenarios where they lose their data/work (e.g., when re-run `theme serve` after working in the Theme Editor).

It focuses on performing checks/helpful-actions during the start-up and auto-pulling files when the theme serve  is running.

This PR doesn't aim to introduce consensus ordering between the CLI and the Theme Editor, mutation history, and ensure conflict-free features in the `Syncer`.

### How to test your changes?

**Sync test case**
- Run `shopify theme serve --theme-editor-sync`
- Open the Theme Editor
- Change something
- Notice the change is synced 
 
with_sync_no_message_and_sync_demo

**Startup case**
- Open the Theme Editor
- Change something
- Run `shopify theme serve --theme-editor-sync`
- Notice the CLI asks which version it should keep
 
modified_version_remotely

#### Other test cases:

<details>
<summary>
<b>
Many updated files localy test case
</b>
</summary>

- With local theme with many modified files
- Run  `shopify theme serve --theme-editor-sync`
- Notice the CLI asks about how to proceed
- Select "Keep the local version" 
- Notice the CLI uploads the JSON files
apply_all
- Also, try the "Keep the remote version"  (notice the CLI will download the JSON files)
- Finally, try the "Merge files"  (notice the CLI will union merge the local and remote the JSON files)

</details>

<details>
<summary>
<b>
Files removed locally (restore test case)
</b>
</summary>

- Remove a JSON file from your local theme
- Run `shopify theme serve --theme-editor-sync`
- Notice the CLI asks before removing the file from your remote development theme
- Recover your JSON file
- Notice the is recovered
startup_recover_local_delete

</details>

<details>
<summary>
<b>
Files removed locally (delete test case)
</b>
</summary>

- Run `shopify theme serve --theme-editor-sync`
- Change `templates/index.json` locally
- Change `templates/index.json` in the Theme Editor
- Notice that users may solve the conflict at the editor
- Delete your JSON file
- Notice the is removed remotely
remove_forever

 
</details>

<details>
<summary>
<b>
<code>theme serve</code> without the <code>--theme-editor-sync</code> flag test case
</b>
</summary>

- Run `shopify theme serve` with modified files locally
- Notice the CLI doesn't ask about conflicts
- Notice that now the Theme Editor message is
  `Customize this theme in the Theme Editor, and use 'theme pull' to get the changes`
- Notice the pulling mechanism is not activated
  regular_diff_message
  dontask_apply_to_all
</details>

### Post-release steps

Include the `--theme-editor-sync` in the [`theme serve`documentation](https://shopify.dev/themes/tools/cli/theme-commands#serve).

### Update checklist

- [x] I've added a CHANGELOG entry for this PR (if the change is public-facing)
- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows).
- [x] I've left the version number as is (we'll handle incrementing this when releasing).
- [x] I've included any post-release steps in the section above (if needed).

### CODE REVIEW

**Review by macournoyer — APPROVED** [review]
Damn! 👏  Nice work. Top hatted... It's magical 🪄 

I skimmed through some parts of the code, but core logic looks right.

What do you think about dropping the value in `--theme-editor-sync=SEC`, just `--theme-editor-sync` w/ a default? I don't see why anyone would want to tweak that? And we can change the default later if it's polling too much.

**Comment by karreiro** [comment]
Awesome idea 🔥 Thank you, @macournoyer! I've applied your suggestion in a new commit :)

**Comment by lesterdefreitas** [comment]
@karreiro thanks so much for this, it's so helpful!

**Comment by adam-ainsworth** [comment]
This really should be more prominent in the documents. I thought I'd lost a couple of hours' work and then discovered this. Resigned to redoing everything, I noticed that there are previous versions of files in the code editor, and I was able to recover my data and schema files. 

If Shopify wants to be taken seriously, they really need to sort this sort of thing out.

**Pull request merged**
