### PR TITLE
Add `-d/--development` flag to Shopify theme pull command.

### LINKED ISSUE #1878: [Min feature] Add --development flag to shopify theme pull command
# Issue summary

Write a short description of the issue here ↓

I've been using Shopify CLI and Github integration almost daily, great tools, thanks for the all the maintainers. The other day, I was working with a Shopify Plus merchant, they have almost 100 themes, and usually my workflow is I run the Shopify theme serve command, then make changes wether it's in the customiser/editor or just in code, but before I turn off the development server, I first pull the saved settings in the customiser with the command `shopify theme pull -n` , this prompt me to select a theme to pull from, but imagine if there is 100 themes or you choose a different theme by mistake. Is it possible to add a flag like with the `--live` but instead `--development` that will be extremely helpfull.

## Expected behavior

What do you think should happen?

`shopify theme pull --development`

Pulls the development theme and chooses the theme without prompting the theme selector.

## Actual behavior

What actually happens?

It's a feature request, there is no implementation for it yet.

## Specifications

- App type:
- Operating System: macOs
- Shell: zsh
- Ruby version (ruby -v): v2.6.8p205

### PR DESCRIPTION
**Pull request by idbakkasse**
### WHY are these changes introduced?

This fixes #1878: Users can't pull the changes from the current development theme to save them after making modification on the local theme customiser.

This saves so much time, and might prevent pulling a different theme especially in stores with 100 themes. 

### WHAT is this pull request doing?

This PR introduces a new flag representing the development theme `-d/--development`. So, now users can perform operations like `shopify theme pull --development` to retrieve the settings made in local theme customiser without being prompt to select/choose the development theme (works just like the `--live` flag)

### How to test your changes?

To test the changes run the following commands after lunching the development server

```shell
shopify theme pull --development
or 
shopify theme pull -d
```

### Post-release steps

Update documentation with the new -d/--development flag at https://shopify.dev/themes/tools/cli/theme-commands#pull

### Update checklist

- [x] I've added a CHANGELOG entry for this PR (if the change is public-facing)
- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows).
- [x] I've left the version number as is (we'll handle incrementing this when releasing).
- [x] I've included any post-release steps in the section above.

### CODE REVIEW

**Comment by idbakkasse** [comment]
Please note that this PR is a continuation of the previous one at #1882 due to Shopify CLA issue. Thanks for your understanding.

**Review by karreiro — COMMENTED** [review]
Thank you for this PR, @idbakkasse 🚀 as I mentioned in the other one, it greatly enhances the development experience!

Also, I'd like to mention 2 details and 1 optional enhancement:


#### 1. Make the new flag visible on `--help`

When users run `shopify theme pull --help`, the new development flag is not appearing:

Screenshot 2022-01-10 at 18 31 23

We may fix that by adding an extra line [here](https://github.com/Shopify/shopify-cli/blob/main/lib/project_types/theme/messages/messages.rb#L193), like this one:
```
{{command:-d, --development}}     Pull theme files from your remote development theme.
```

#### 2. Changelog

We may add this PR the [CHANGELOG.md](https://github.com/Shopify/shopify-cli/blob/main/CHANGELOG.md?plain=1#L4) by adding a line like this:
```
* [#1900](https://github.com/Shopify/shopify-cli/pull/1900): Add `-d'/`--development` flag to Shopify theme pull command
```


#### 3. `theme pull` and `theme push` (optional)
It's nice to keep `pull` and `push` commands synced in this kind of use case, so users may expect that if something works for `pull`, it works for `push` as well. Thus, we could also add the `--development` flag in the [`push.rb`](https://github.com/Shopify/shopify-cli/blob/main/lib/project_types/theme/commands/push.rb#L13).


\-

Thanks again for this enhancement!  :)

**Comment by idbakkasse** [comment]
@karreiro Thanks you so much for your details, that was extremely helpful, I did all as you said, except for that last feature;
3. Add the flag to `theme push` just like `theme pull` (optional) 
Since the `theme push` command already has the flag so need to change that. 

Thanks for reviewing this PR!

**Review by karreiro — APPROVED** [review]
Thank you, @idbakkasse! Great stuff 🚀

**Comment by idbakkasse** [comment]
@karreiro Take your time and thanks again for your help.

**Comment by karreiro** [comment]
The "Acceptance Tests" suite was fixed by https://github.com/Shopify/shopify-cli/pull/1921.

I've rebased/run the suite with this PR locally, and they pass.

**Pull request merged**
