### PR TITLE
[Scripts] Update package name for TS checkout scripts

### PR DESCRIPTION
**Pull request by adampetro**
### WHY are these changes introduced?

See https://github.com/Shopify/script-service/issues/3870

### WHAT is this pull request doing?

Update the package name of the TypeScript checkout library.

### How to test your changes?

Prerequisites: 
- Set yourself up to use Scripts (instructions [here](https://shopify.dev/apps/checkout/scripts/setup))
- Enable the `scripts_beta_languages` feature in the CLI (used [here](https://github.com/Shopify/shopify-cli/blob/e89cb4c018e40d84227f937000cec63a93d6a8e2/lib/project_types/script/layers/application/extension_points.rb#L31))

Steps:
1. Create a new script from your app by running `shopify script create --branch=ap/checkout-api-library-name-shuffle` (the `--branch` flag tells the CLI to bootstrap from that branch of the [scripts-apis-examples](https://github.com/Shopify/scripts-apis-examples) repo, which should not be merged until this change is merged and released).
2. Select one of `shipping-methods` or `payment-methods` as the API.
3. Select one of `assemblyscript` or `typescript` as the language.
4. As instructed by the CLI, once the script is created, `cd` into its directory.
5. Run `npm test` and ensure that the tests pass.
6. Run `shopify script push` to push your script. No error should occur and it should appear at `https://partners.shopify.com/<partner-org-id>/apps/<app-id>/extensions`.
7. Repeat 1-6 until all 4 combinations of API and language have been exhausted. Note that I tested all 4 so feel free to only test a subset.

### Post-release steps

Merge https://github.com/Shopify/scripts-apis-examples/pull/14

### Update checklist

- [x] I've added a CHANGELOG entry for this PR (if the change is public-facing)
- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows).
- [x] I've left the version number as is (we'll handle incrementing this when releasing).
- [x] I've included any post-release steps in the section above.

### CODE REVIEW

**Comment by pepibumur** [comment]
> This cannot be tophatted until Shopify/scripts-apis#456 has been merged and version 2.0.0 of @shopify/scripts-checkout-apis published to NPM

@adampetro let me know when it's ready and I'll tophat it end-to-end

**Comment by adampetro** [comment]
> let me know when it's ready and I'll tophat it end-to-end

@pepibumur it is ready for :tophat:ing now. Thanks!

**Comment by jacobsteves** [comment]
I'm getting an error when trying to push: `Script can't be created because API library @shopify/scripts-checkout-apis is missing from the dependencies This error can occur because the API library was removed from your system or there is a problem with dependencies in the repository.`. Looks like thats because the example script still uses the old name?

**Review by jacobsteves — APPROVED** [review]
🎩 👍

**Review by andrewhassan — APPROVED** [review]

**Pull request merged**
