### PR TITLE
Fix `theme pull` error when pulling images

### LINKED ISSUE #1315: Image errors on "shopify theme pull"
# Issue summary

When attempting to pull a theme that has images (jpg or png) in the assets folder, errors are generated and the image files aren't pulled correctly. They're all downloaded at zero bytes.

## Expected behavior

Images should be downloaded.

## Actual behavior

What actually happens?

Images are flagged as errors as in the following examples....
Screenshot 2021-06-30 at 16 25 16

<details>
<code>
┃ ERROR get assets/password-page-background.jpg: "\xFF" from ASCII-8BIT to UTF-8
┃ ERROR get assets/site-background.jpg: "\xFF" from ASCII-8BIT to UTF-8
</code>
</details>

## Steps to reproduce the problem

Use "shopify theme pull" command on a theme that has an image in the assets folder

## Specifications

- Operating System: Mac OS 11.4
- Shell: zsh
- Ruby version (ruby -v): 3.0.1

### PR DESCRIPTION
**Pull request by macournoyer**
### WHY are these changes introduced?

Fixes #1315

### WHAT is this pull request doing?

Write in binary mode when the asset is returned as a base64 encoded attachment.

Top hatted w/ images.

### Update checklist

- [x] I've added a CHANGELOG entry for this PR (if the change is public-facing)
- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows).
- [x] I've left the version number as is (we'll handle incrementing this when releasing).

### CODE REVIEW

**Comment by macournoyer** [comment]
> I got "no implicit conversion of Hash into Integer" Error.

@alquezajanmaverick Do you get a backtrace after this error is shown?

If not, can you reproduce again w/ the environment variable `DEBUG=1` set? So I get a backtrace. I think on Windows that's how you do it:

```
cmd /C "set DEBUG=1 && shopify theme pull"
```

**Comment by alquezajanmaverick** [comment]
**no implicit conversion of Hash into Integer**
```
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/theme/file.rb:25:in `write'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/theme/file.rb:25:in `write'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/theme/file.rb:25:in `write'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/theme/syncer.rb:259:in `get'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/theme/syncer.rb:207:in `perform'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/theme/syncer.rb:104:in `block (3 levels) in start_threads'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/theme/syncer.rb:101:in `loop'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/theme/syncer.rb:101:in `block (2 levels) in start_threads'
```

**Comment by alquezajanmaverick** [comment]
> > I got "no implicit conversion of Hash into Integer" Error.
> 
> @alquezajanmaverick Do you get a backtrace after this error is shown?
> 
> If not, can you reproduce again w/ the environment variable `DEBUG=1` set? So I get a backtrace. I think on Windows that's how you do it:
> 
> ```
> cmd /C "set DEBUG=1 && shopify theme pull"
> ```

@macournoyer 
**no implicit conversion of Hash into Integer**
```
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/theme/file.rb:25:in `write'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/theme/file.rb:25:in `write'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/theme/file.rb:25:in `write'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/theme/syncer.rb:259:in `get'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/theme/syncer.rb:207:in `perform'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/theme/syncer.rb:104:in `block (3 levels) in start_threads'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/theme/syncer.rb:101:in `loop'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/theme/syncer.rb:101:in `block (2 levels) in start_threads'
```

**Comment by macournoyer** [comment]
Thanks for the backtrace @alquezajanmaverick! I wasn't able to reproduce, but latest commit should fix it.

**Review by mkevinosullivan — APPROVED** [review]

**Pull request merged**
