### PR TITLE
Revert "Enable Theme Kit Access passwords"

### PR DESCRIPTION
**Pull request by gonzaloriestra**
Related to https://github.com/Shopify/shopify-cli-planning/issues/365

Reverts Shopify/shopify-cli#2558

[We are not releasing this yet](https://shopify.slack.com/archives/C03LLM1GCT0/p1661757349611749?thread_ts=1661508022.436979&cid=C03LLM1GCT0), but we will wait until `theme serve` support and the documentation are ready.

### CODE REVIEW

**Review by pepicrft — APPROVED** [review]

**Comment by curiouscrusher** [comment]
Well that was short lived, any news on the revised release timeline @gonzaloriestra?

**Comment by gonzaloriestra** [comment]
@curiouscrusher we aim to release it in late September

**Comment by kenji-twp** [comment]
+1

**Comment by curiouscrusher** [comment]
Hope it ships soon!

**Comment by kenji-twp** [comment]
> @curiouscrusher @kenji-twp it was was finnally shipped! And now you can also work on themes with the new CLI (3.x).
> 
> 
> 
> More info:
> 
> 
> 
> https://shopify.dev/themes/tools/cli
> 
> https://shopify.dev/themes/tools/cli/ci-cd

Thanks @gonzaloriestra ! Very exciting news!! 👏

**Pull request merged**
