### PR TITLE
[Feature] Add new Theme CLI commands: `theme list` and `theme open`

### PR DESCRIPTION
**Pull request by karreiro**
### WHY are these changes introduced?

Partners (#1867) need a command to list themes connected to their store and a command for opening the preview of a specific theme.

### WHAT is this pull request doing?

This PR introduces:
- the `theme list` command, which provides the list of themes connected to the current store; and
- the `theme open` command, which quickly provides a preview of the selected theme (this command accepts the following options: `-t, --theme=NAME_OR_ID`, `-l, --live`, and `-d, --development`).

From the code perspective, this PR introduces presenter classes to take care of the presenting logic. Thus, we've avoided duplication between `Theme::Forms::Select` and the new `Theme::Command::List`.

Also, this PR renames occurrences of the **Online Store Editor** term in favor of **Theme Editor**.

### How to test your changes?

- Run `shopify theme list` and see the list of themes
- Run `shopify theme list -h` and see the help message
- Run `shopify theme open` and select a theme
- Run `shopify theme open -d` and open the development theme
- Run `shopify theme open -l` and open the live theme
- Run `shopify theme open -h` and see the help message

list

open_d

<details><summary><b>Click here</b> to see the other screenshots</summary>

<br />

**List**

list_help

<br /><br />

**Open**

open_help
open_t_name
open_t_id
open_l
open_l

</details>

### Post-release steps

Include the `theme list` and the `theme open` commands in the [documentation](https://shopify.dev/themes/tools/cli/theme-commands).

### Update checklist

- [x] I've added a CHANGELOG entry for this PR (if the change is public-facing)
- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows).
- [x] I've left the version number as is (we'll handle incrementing this when releasing).
- [x] I've included any post-release steps in the section above.

### CODE REVIEW

**Review by macournoyer — APPROVED** [review]
Damn! This is so nice. Love the refactoring too 👏

**Comment by lesterdefreitas** [comment]
@karreiro Absolutely awesome. Would it be possible to also have a command to open up the editor for each theme? With themekit you would use `theme open -e=[env_name] -E` and it would open the editor. It would be amazing if we could, for instance: `shopify theme open -d -E` to quickly open the editor for our dev themes.

**Comment by lesterdefreitas** [comment]
@karreiro awesome, thank you! And just to add, after testing, I see that the theme open command doesn't actually open the theme. It just prints the theme links in the terminal. Or is something wrong on my end?

**Comment by karreiro** [comment]
@lesterdefreitas you're absolutely correct. The CLI should actually open the theme in the browser https://github.com/Shopify/shopify-cli/issues/2210.

**Pull request merged**
