### PR TITLE
Added Windows install instructions to Shopify-CLI Installation Docs

### PR DESCRIPTION
**Pull request by HeavenlyEntity**
RubyGems does not specify installation for windows users who have no experience with ruby. Added installation instructions to be more specific.

### WHY are these changes introduced?
 
Clearer installation process for windows users.

Fixes #0000 

### WHAT is this pull request doing?
Updating installation documentation for windows users and nothing is specified on how to install RubyGems on their site with windows. As it's only for Linux Kernel-based systems.

### How to test your changes?
N.A - Just easy steps to follow for windows users.

### Post-release steps
N.A

### Update checklist

- [x] I've added a CHANGELOG entry for this PR (if the change is public-facing)
- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows).
- [x]  I've left the version number as is (we'll handle incrementing this when releasing).
- [x] I've included any post-release steps in the section above.

### CODE REVIEW

**Comment by HeavenlyEntity** [comment]
CLA Signed ✔

**Comment by gonzaloriestra** [comment]
@HeavenlyEntity thanks for the contribution! ❤️ 

But instead of updating that file and trying to keep it in sync, maybe we could just add a link to https://shopify.dev/apps/tools/cli/installation, which is more complete. What do you think @MeredithCastile @shainaraskas?

**Comment by shainaraskas** [comment]
@gonzaloriestra agree - Ideally we'd remove the install instructions from here completely and link out to avoid confusion.

**Comment by gonzaloriestra** [comment]
I've finally added the link in https://github.com/Shopify/shopify-cli/pull/2062, so I think we can close here. Thank you anyway!

**Pull request closed without merging**
