### PR TITLE
Improve `theme serve` errors and add logs for successful operations

### PR DESCRIPTION
**Pull request by karreiro**
This PR introduces two new kinds of log messages for users when they are running a `theme serve` session (**fixed** and **synced**):

Screenshot 2021-11-24 at 14 46 25

Now, users get ~a status~ feedback when something happens with a file:
- **Error** - An error has occurred (e.g., a liquid template in an invalid state)
- **Synced** - The local version was successfully uploaded
- **Fixed** - An error was fixed

### WHY are these changes introduced?

These changes address concerns about the error logs raised by the following issues:
- https://github.com/Shopify/shopify-cli/issues/1397 
- https://github.com/Shopify/shopify-cli/issues/1612 

Now, users get feedback (with a **status** and a **timestamp**) when they sync or fix an error in a file.

### WHAT is this pull request doing?

This PR introduces a `ShopifyCLI::Theme::Syncer::StandardReporter` in the syncer class to report non-error messages.

Also, the `ShopifyCLI::Theme::Syncer` has a more generic API now. Instead of `Syncer#delay_errors!` and `Syncer#report_errors!`, we have `Syncer#lock_io!` and `Syncer#unlock_io!` enabling/disabling **reporters**.

So, each reporter is responsible for handling their behavior when they enable/disable.

Finally, the `ShopifyCLI::Theme::Syncer::Operation` is responsible for the multiple versions of operation as a string.

### How to test your changes?

Run the `shopify theme serve`, update some theme files, and check the log of `shopify theme serve`:

Kapture 2021-11-24 at 14 48 20

### Update checklist

- [x] I've added a CHANGELOG entry for this PR (if the change is public-facing)
- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows).
- [x] I've left the version number as is (we'll handle incrementing this when releasing).
- [ ] I've included any post-release steps in the section above.

### CODE REVIEW

**Comment by karreiro** [comment]
Thanks for the comments, @macournoyer!

The `Unchanged` state aims to cover this scenario:

Kapture 2021-11-23 at 15 39 38

I've disabled the `Unchanged` state in the GIF above. Thus, when users fix an error locally, they don't know they actually fixed it (because the file doesn't need to sync). This issue was raised by https://github.com/Shopify/shopify-cli/issues/1612.

Alternatively (1), we could keep track of the files with errors in the session. Then, we would show the `Unchanged` state only when users fix an error, but I'm not sure if that would break users expectation.

Alternatively (2), we could implement a mechanism to clean errors from the terminal:

image

I personally find the current approach more consistent, but the alternatives 1 and 2 seem like fair approaches as well. What do you think? :)

**Comment by macournoyer** [comment]
Ah I get it for the error. Seems fair for this scenario to show the error was fixed.

But outside of this scenario, what's the value in outputting it each time:
Screen Shot 2021-11-23 at 2 13 54 PM
m 

Perhaps as you say, it should only be shown after an "Error" state. IMO it should be shown as "Fixed" instead of "Unchanged".

Do you think that's doable, and would make sense?

**Comment by karreiro** [comment]
Yes, and it makes total sense! 🚀

Thanks for the suggestions, @macournoyer. I'll update the PR in that direction soon :-)

**Review by macournoyer — APPROVED** [review]
AWESOME! AWESOME! 🤩 
Thanks for doing that adjustment. I love everything about this ❤️

**Pull request merged**
